=== Lehirti/Lehirti-Game-Engine/JAXBInterfaces/schema/event.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:simpleType name="image_or_text_reference">
   <xs:restriction base="xs:string">
     <xs:pattern value="([a-z\.]+\.[A-Za-z0-9\.$]+\.)?[A-Z][A-Z_]*"/>
   </xs:restriction>
 </xs:simpleType>
 
 <xs:simpleType name="event_reference">
   <xs:restriction base="xs:string">
     <xs:pattern value="[a-z\.A-Z0-9]{1,}"/>
   </xs:restriction>
 </xs:simpleType>
 
 <xs:simpleType name="key_type">
   <xs:restriction base="xs:string">
     <xs:enumeration value="Q"></xs:enumeration>
     <xs:enumeration value="LEAVE"></xs:enumeration>
     <xs:enumeration value="NORTH"></xs:enumeration>
     <xs:enumeration value="ENTER"></xs:enumeration>
     <xs:enumeration value="A"></xs:enumeration>
     <xs:enumeration value="WEST"></xs:enumeration>
     <xs:enumeration value="SOUTH"></xs:enumeration>
     <xs:enumeration value="EAST"></xs:enumeration>
     <xs:enumeration value="Z"></xs:enumeration>
     <xs:enumeration value="X"></xs:enumeration>
     <xs:enumeration value="C"></xs:enumeration>
     <xs:enumeration value="V"></xs:enumeration>
   </xs:restriction>
 </xs:simpleType>

 <xs:element name="event">
   <xs:complexType>
     <xs:sequence>
       <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
       <xs:element name="todo" type="xs:string" minOccurs="0" maxOccurs="1"/>
       <xs:element name="extensions" minOccurs="0" maxOccurs="1">
         <xs:complexType>
           <xs:sequence>
             <xs:element name="extension" minOccurs="1" maxOccurs="unbounded">
               <xs:complexType>
                 <xs:attribute name="event" type="event_reference" use="required"/>
                 <xs:attribute name="key" type="key_type" use="optional"/>
                 <xs:attribute name="text" type="image_or_text_reference" use="required"/>
               </xs:complexType>
             </xs:element>
           </xs:sequence>
         </xs:complexType>
       </xs:element>
       <xs:element name="images" minOccurs="0" maxOccurs="1">
         <xs:complexType>
           <xs:sequence>
             <xs:element name="bg" type="image_or_text_reference" minOccurs="0" maxOccurs="1"/>
             <xs:element name="fg" type="image_or_text_reference" minOccurs="0" maxOccurs="unbounded"/>
           </xs:sequence>
           <xs:attribute name="clearBackground" default="false" type="xs:boolean" use="optional"/>
           <xs:attribute name="clearForeground" default="true" type="xs:boolean" use="optional"/>
         </xs:complexType>
       </xs:element>
       <xs:element name="texts">
         <xs:complexType>
           <xs:sequence>
             <xs:element name="text" type="image_or_text_reference" minOccurs="1" maxOccurs="unbounded"/>
           </xs:sequence>
         </xs:complexType>
       </xs:element>
       <xs:element name="options">
         <xs:complexType>
           <xs:sequence>
             <xs:element name="option" minOccurs="1" maxOccurs="12">
               <xs:complexType>
                 <xs:attribute name="key" type="key_type" use="optional"/>
                 <xs:attribute name="text" type="image_or_text_reference" use="required"/>
                 <xs:attribute name="event" type="event_reference" use="required"/>
               </xs:complexType>
             </xs:element>
           </xs:sequence>
         </xs:complexType>
       </xs:element>
     </xs:sequence>
     <xs:attribute name="version" type="xs:positiveInteger" use="optional"/>
   </xs:complexType>
 </xs:element>
</xs:schema>

=== Lehirti/Lehirti-Game-Engine/JAXBInterfaces/examples/Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<event xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/event.xsd">
  <description></description> <!-- optional: Can be used to describe what this event is all about -->
  <todo></todo> <!-- optional: Can be used to describe things that need to be coded manually -->
  <extensions> <!-- extensions allow you to add a "to-this-event" option to others events -->
     <!-- in this example: during the FindWatch event there will be an option on the "Z" button, to go to this event -->
     <extension event="crashsite.FindWatch" key="Z" text="OPTION_BACK_TO_AIRPORT"/>
  </extensions>
  <images clearBackground="true" clearForeground="true"> <!-- optionally clear background/foreground images from previous events -->
    <bg>EXAMPLE_BACKGROUND</bg> <!-- set a new background image; in this example a new image key will be created inside the generated event class -->
    <fg>EXAMPLE_FOREGROUND</fg> <!-- add a new foreground image; in this example a new image key will be created inside the generated event class -->
    <fg>intro.IntroImage.AIRPORT</fg> <!-- add a new foreground image; in this example a previously existing image key will be used -->
  </images>
  <texts> <!-- text to display in the text area; text from previous events will always be cleared -->
    <text>EXAMPLE_DESCRIPTION</text> <!-- the naming is the same as image keys; here the "create new text key in generated event class" example -->
    <text>intro.Bus.Text.BUS_DESCRIPTION</text>
  </texts>
  <options>
    <!-- key: the name of one of the 12 option keys; optional; if not specified, the game will pick a free key -->
    <!-- text: a text key for the text in the option area -->
    <!-- event: fully-qualified name of the target event; this event must have a default constructor; description on how to reference other "xml" events will come later -->
    <option key="ENTER" text="OPTION_EXAMPLE" event="intro.Airport"/>
  </options>
</event>
